version: '3.3'
services:
  service1:
    build:
      context: /opt/micservice/
    image: webapicompose
    ports:
      - 44380:80/tcp
    command: ["dotnet","app/MicServiceWebApi"]
    volumes:
    - /opt/micservice_api/apiconfig/appsettings5727.json:/app/appsettings.json
  service2:
    image: webapicompose
    ports:
      - 44381:80/tcp
    command: ["dotnet","app/MicServiceWebApi"]
    volumes:
    - /opt/micservice_api/apiconfig/appsettings5728.json:/app/appsettings.json